mkdir -p .streamlit
touch .streamlit/secrets.toml
# OpenAI API Configuration
OPENAI_API_KEY = "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" 
